language: node_js
node_js:
  - "5.7"
  - "4.3"
  - "0.12"
  - "0.10"

script:
  - npm install
  - npm build
  - npm release

notifications:
  email:
    - victoria.french@cinecove.com

git:
  depth:
    10

cache:
  directories:
    - node_modules
